name: Adventure CI/CD pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/adventure/**'
      - '.github/workflows/adventure-fbackend-ci-cd.yml'
      - '_infra/**'

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build Orleans Server Docker Image
        id: build-server
        uses: docker/build-push-action@v6
        with:
          context: ./src/adventure/src/AdventureServer
          push: true

      - name: Build Orleans Client Docker Image
        id: build-client
        uses: docker/build-push-action@v6
        with:
          ccontext: ./src/adventure/src/AdventureClient
          push: true


    