name: Adventure CI/CD pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: latest

jobs:
  build:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies for Backend
        run: dotnet restore /src/adventure/src/AdventureGame.sln

      - name: Build Backend
        run: dotnet build /src/adventure/src/AdventureGame.sln --configuration Release --no-restore


    